package dream

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/anthropics/agentjit/internal/config"
	"github.com/anthropics/agentjit/internal/ingest"
	"github.com/anthropics/agentjit/internal/skills"
)

// BuildContext creates the context payload string for the dream compiler.
func BuildContext(events []ingest.Event, existingSkills []skills.SkillMeta, cfg config.Config) (string, error) {
	var sb strings.Builder

	sb.WriteString("## EXECUTION LOGS\n\n")
	for _, event := range events {
		data, err := json.Marshal(event)
		if err != nil {
			continue
		}
		sb.Write(data)
		sb.WriteByte('\n')
	}

	sb.WriteString("\n## EXISTING SKILLS INVENTORY\n\n")
	if len(existingSkills) == 0 {
		sb.WriteString("No existing skills.\n")
	} else {
		for _, skill := range existingSkills {
			sb.WriteString(fmt.Sprintf("### %s\n", skill.Name))
			sb.WriteString(fmt.Sprintf("- Description: %s\n", skill.Description))
			sb.WriteString(fmt.Sprintf("- Scope: %s\n", skill.Scope))
			sb.WriteString(fmt.Sprintf("- Path: %s\n", skill.Path))
			sb.WriteString(fmt.Sprintf("- Generated by: %s\n\n", skill.GeneratedBy))
			if skill.RawContent != "" {
				sb.WriteString("Full content:\n```\n")
				sb.WriteString(skill.RawContent)
				sb.WriteString("\n```\n\n")
			}
		}
	}

	return sb.String(), nil
}

// BuildPrompt reads the compiler prompt template and replaces config variables.
func BuildPrompt(promptPath string, cfg config.Config, globalSkillsDir string) (string, error) {
	data, err := os.ReadFile(promptPath)
	if err != nil {
		return "", fmt.Errorf("reading prompt: %w", err)
	}

	prompt := string(data)

	replacements := map[string]string{
		"{{MIN_PATTERN_FREQUENCY}}":    strconv.Itoa(cfg.Dream.MinPatternFrequency),
		"{{MIN_TOKEN_SAVINGS}}":        strconv.Itoa(cfg.Dream.MinTokenSavings),
		"{{DEPRECATE_AFTER_SESSIONS}}": strconv.Itoa(cfg.Dream.DeprecateAfterSessions),
		"{{GLOBAL_SKILLS_DIR}}":        globalSkillsDir,
		"{{GLOBAL_CLI_TOOLS}}":         strings.Join(cfg.Scope.GlobalCLITools, ", "),
	}

	for key, val := range replacements {
		prompt = strings.ReplaceAll(prompt, key, val)
	}

	return prompt, nil
}

// RunDream executes the full dream compilation sequence.
func RunDream(paths config.Paths, cfg config.Config, promptPath string) error {
	start := time.Now()

	// 1. Gather unprocessed logs
	fmt.Print("[AgentJIT] Gathering unprocessed logs... ")
	events, err := GatherUnprocessedLogs(paths, cfg.Dream.MaxContextLines)
	if err != nil {
		return fmt.Errorf("gathering logs: %w", err)
	}

	if len(events) == 0 {
		fmt.Println("no new events to process")
		return nil
	}
	fmt.Printf("%d events\n", len(events))

	// 2. Gather existing skills
	fmt.Print("[AgentJIT] Scanning existing skills... ")
	existingSkills, _ := skills.ScanSkillsDir(paths.Skills)
	fmt.Printf("%d skills\n", len(existingSkills))

	// 3. Build context
	fmt.Print("[AgentJIT] Building compiler context... ")
	context, err := BuildContext(events, existingSkills, cfg)
	if err != nil {
		return fmt.Errorf("building context: %w", err)
	}
	fmt.Printf("%d bytes\n", len(context))

	// 4. Build prompt
	prompt, err := BuildPrompt(promptPath, cfg, paths.Skills)
	if err != nil {
		return fmt.Errorf("building prompt: %w", err)
	}

	// 5. Write context to temp file
	tmpFile, err := os.CreateTemp("", "agentjit-dream-*.jsonl")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	defer os.Remove(tmpFile.Name())
	tmpFile.WriteString(context)
	tmpFile.Close()

	// 6. Invoke Claude
	sessionID := uuid.New().String()
	fmt.Printf("[AgentJIT] Starting dream compilation (%d events, %d existing skills)\n",
		len(events), len(existingSkills))
	fmt.Printf("[AgentJIT] Session: %s\n", sessionID)
	fmt.Printf("[AgentJIT] Attach from another terminal: claude --resume %s\n", sessionID)

	cmd := exec.Command("claude",
		"--print",
		"--session-id", sessionID,
		"--name", "agentjit-dream",
		"-p", prompt,
		"--allowedTools", "Read,Write,Bash,Glob,Grep",
	)

	contextData, _ := os.ReadFile(tmpFile.Name())
	cmd.Stdin = strings.NewReader(string(contextData))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("running claude: %w", err)
	}

	// 7. Update marker
	if err := WriteMarker(paths.DreamMarker, time.Now().UTC()); err != nil {
		return fmt.Errorf("writing marker: %w", err)
	}

	elapsed := time.Since(start).Round(time.Second)
	fmt.Printf("[AgentJIT] Dream compilation complete (%s)\n", elapsed)
	return nil
}
